---
- name: Apt Cache aktualisieren
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Benoetigte Systempakete installieren
  ansible.builtin.apt:
    name: "{{ system_packages }}"
    state: present

- name: UFW eingehend standardmaessig blockieren
  community.general.ufw:
    direction: incoming
    policy: deny

- name: UFW ausgehend standardmaessig erlauben
  community.general.ufw:
    direction: outgoing
    policy: allow

- name: SSH in UFW erlauben
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: UFW aktivieren
  community.general.ufw:
    state: enabled
