Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.hostname = "jupyter-node"

  config.vm.define "jupyter-node" do |node|
    node.vm.network "private_network", ip: "192.168.56.20"

    node.vm.provider "virtualbox" do |vb|
      vb.name = "jupyter-node"
      vb.memory = 2048
      vb.cpus = 2
    end
  end
end
